Ayomide/testsuit
polytope-labs/hyperbridge pull request #115
Opened 2024-03-08 13:10 UTC by Adebara123

2024-03-09 15:27 UTC, Wizdave97 requested changes

2024-03-09 15:27 UTC, Wizdave97 commented on modules/ismp/testsuite/src/lib.rs
> +/// The State machine for the proxy is assumed in this test to be ``StateMachine::Ethereum(Ethereum::ExecutionLayer)``
This documentation is wrong, the proxy state machine is Kusam(2000).

2024-03-09 15:27 UTC, Wizdave97 commented on modules/ismp/testsuite/src/lib.rs
> +pub fn prevent_request_timeout_on_proxy_with_known_state_machine<H, D>(host: &H, dispatcher: &D)  -> Result<(), &'static str>
Allow the consumer of the test specify what the proxy_state_machine is and what the directly connected chain is for the purpose of the test.

2024-03-09 15:27 UTC, Wizdave97 commented on modules/ismp/testsuite/src/lib.rs
> +let destination_consensus_client_id = consensus_clients.iter().find(|client| client.state_machine(direct_conn_state_machine).ok().is_some()).expect("The proxy destination chain's consensus client sho
```suggestion
let destination_consensus_client_id = consensus_clients.iter().find(|client| client.state_machine(direct_conn_state_machine).ok().is_some()).expect("The directly connected chain's consensus client should be set for this test").consensus_client_id();
```

2024-03-09 15:27 UTC, Wizdave97 commented on modules/ismp/testsuite/src/lib.rs
> +let  destiation_client_= &consensus_clients[0].consensus_client_id();
Why is this still here?

2024-03-09 15:27 UTC, Wizdave97 commented on modules/ismp/testsuite/src/lib.rs
> +let post = Post {
This post is not correct for the purposes of this test

2024-03-09 15:27 UTC, Wizdave97 commented on modules/ismp/testsuite/src/lib.rs
> +handle_incoming_message(host, timeout_message).unwrap();
Why are there two timeout checks?

2024-03-11 10:27 UTC, Adebara123 commented
@Wizdave97 All requested changes have been resolved. Please look into it.

2024-03-13 15:00 UTC, Wizdave97 commented on modules/ismp/testsuite/src/lib.rs
> +use std::process::id;
```suggestion

```

2024-03-13 15:01 UTC, Wizdave97 commented on modules/ismp/testsuite/src/lib.rs
> +                state_id: StateMachine::Bsc,
revert this
```suggestion
                state_id: StateMachine::Bsc,
```

2024-03-13 15:02 UTC, Wizdave97 commented on modules/ismp/testsuite/src/mocks.rs
> +pub const MOCK_CONSENSUS_CLIENT_ID_2: [u8; 4] = [2u8; 4];
```suggestion
pub const MOCK_PROXY_CONSENSUS_CLIENT_ID: [u8; 4] = [2u8; 4];
```

2024-03-13 15:04 UTC, Wizdave97 commented on modules/ismp/testsuite/src/lib.rs
> +    let intermediate_state = setup_mock_client(host);
Only the proxy needs to be setup for this test.
```suggestion
    let intermediate_state = setup_mock_client(host);
```

2024-03-13 15:04 UTC, Wizdave97 commented on modules/ismp/testsuite/src/lib.rs
> +    // Assert that the dispatch results are empty
```suggestion
    // Assert that the dispatch results are empty which means the timeout message was ignored.
```

2024-03-18 14:44 UTC, Wizdave97 approved these changes

2024-03-18 14:48 UTC, Wizdave97 commented
Update the branch

2024-03-18 17:57 UTC, Adebara123 commented
@Wizdave97  Branch updated

2024-03-19 08:03 UTC, merged