State Machine Freezer
polytope-labs/hyperbridge pull request #79
Opened 2024-01-22 13:37 UTC by dharjeezy

2024-01-23 13:59 UTC, Wizdave97 commented on parachain/modules/ismp/pallet/src/host.rs
> +            if frozen == true {
```suggestion
            if frozen {
```

2024-01-23 14:01 UTC, Wizdave97 commented on parachain/modules/ismp/testsuite/src/mocks.rs
> +            .map(|frozen| frozen == true)
```suggestion
```

2024-01-23 14:01 UTC, Wizdave97 commented on parachain/modules/state-machine-freezer/Cargo.toml
> +name = "pallet-state-machine-freezer"
```suggestion
name = "state-machine-manager"
```

2024-01-23 14:03 UTC, Wizdave97 requested changes

2024-01-23 14:03 UTC, Wizdave97 commented on parachain/modules/state-machine-freezer/Cargo.toml
> +name = "pallet-state-machine-freezer"
```suggestion
name = "state-machine-manager"
```

2024-01-23 15:23 UTC, seunlanlege commented on Cargo.toml
> +      "evm/abi", "parachain/modules/relayer-fees", "parachain/modules/state-machine-manager",
Should all be on new lines

2024-01-23 15:30 UTC, Wizdave97 commented on parachain/runtimes/gargantua/src/lib.rs
> +        StateMachineManager: state_machine_manager = 45,
The pallet config is not implemented for the runtime

2024-01-23 17:07 UTC, seunlanlege commented on parachain/modules/state-machine-manager/Cargo.toml
> +edition = "2021"
author and description

2024-01-24 07:40 UTC, Wizdave97 approved these changes

2024-01-24 08:15 UTC, seunlanlege approved these changes

2024-01-24 12:44 UTC, merged